---
title: "HH Income
author: "Anthony Gallegos"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: yes
---

```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE}
library(knitr)
library(dplyr)
library(pander)
library(devtools)
library(censusapi)
library(maptools)
library(rgdal)
library(geojsonio)
library(rmapshaper)
library(sf)
library(ggplot2)
library(tidyr)
library(viridis)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


# Data Pull Code for HH Income

## This is not using the 2010 sf1 data, as it is not included. Instead, the acs/ac5 data will be used.

```{r}

# Set Working Directory
setwd("~/Documents/Capstone/Solo Project/Markdown")

# Census Key
censuskey <- "e2a75a26c7d4adf9db476fa739110c582113d15e"

```

## 1990 Decennial Data Pull
```{r}

# Var Pull

`1990_HH_inc` <- read.csv("/home/anthony/Documents/Capstone/Solo Project/Variables/hh_inc/hh_1990.csv")

# Create Variable list based off variables in the first column
var.hhinc.1990 <- `1990_HH_inc`$name


# Pull Data using variable list only. Make sure the censusapi package is loaded.
hh.inc.1990 <- getCensus( name = "sf3", vintage = 1990, key=censuskey,
                               vars = var.hhinc.1990,
                               region="tract:*", regionin="state:04&county:013" )



# Rename data
hh.inc.1990 <- rename(hh.inc.1990, Household_Income_1990=P080A001 )
```


## 2000 Decennial Data Pull
```{r}

# Var Pull

`2000_HH_inc` <- read.csv("/home/anthony/Documents/Capstone/Solo Project/Variables/hh_inc/hh_2000.csv")

# Create Variable list based off variables in the first column
var.hhinc.2000 <- `2000_HH_inc`$name


# Pull Data using variable list only. Make sure the censusapi package is loaded.
hh.inc.2000 <- getCensus( name = "sf3", vintage = 2000, key=censuskey,
                               vars = var.hhinc.2000,
                               region="tract:*", regionin="state:04&county:013" )



# Rename data
hh.inc.2000 <- rename(hh.inc.2000, Household_Income_1990=P053001 )
```


## 2010 ACS Data Pull
```{r}

# It may be necessary to pull the 2010 ACS because the 2010 decennial sf1 data is not nearly as comprehensive.

`2010acs_HH_inc` <- read.csv("/home/anthony/Documents/Capstone/Solo Project/Variables/hh_inc/hh_inc_2010acs.csv")

# Create Variable list based off variables in the first column
var.hhinc.2010acs <- `2010acs_HH_inc`$name


# Pull Data using variable list only. Make sure the censusapi package is loaded.
hh.inc.2010acs <- getCensus( name = "acs/acs5", vintage = 2010, key=censuskey,
                               vars = var.hhinc.2010acs,
                               region="tract:*", regionin="state:04&county:013" )



# Rename data
hh.inc.2010acs <- rename(hh.inc.2010acs, Household_Income_2010=B19013_001E )
```

# Exploratory Fun
```{r}
mcpa <- left_join(hh.inc.2010acs, edu.2010acs, by="tract")

write.csv( mcpa, "/home/anthony/Documents/Capstone/Solo Project/Written CSVs/mcpa.csv", row.names=T)


```




